# Generated by Django 5.0.6 on 2024-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cetPhysics', models.CharField(max_length=10)),
                ('cetChemistry', models.CharField(max_length=10)),
                ('cetMathematics', models.CharField(max_length=10)),
                ('cetPercentile', models.CharField(max_length=10)),
                ('jeePhysics', models.CharField(max_length=10)),
                ('jeeChemistry', models.CharField(max_length=10)),
                ('jeeMathematics', models.CharField(max_length=10)),
                ('jeePercentile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhMerit', models.CharField(max_length=20)),
                ('aiMerit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pnumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applNo', models.CharField(max_length=20)),
                ('meritfile', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='documentModel',
        ),
        migrations.DeleteModel(
            name='studentData',
        ),
    ]
