# Generated by Django 5.0.6 on 2024-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_agree_exam_merit_parent_student_uploaddoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddoc',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='uploaddoc',
            name='applNo',
            field=models.CharField(max_length=100),
        ),
    ]
