# Generated by Django 5.0.6 on 2024-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_uploaddoc_file_path_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddoc',
            name='applNo',
            field=models.CharField(max_length=200),
        ),
    ]
